version: "1.0"
services:
  # ? Configuracion main-back
  hydrometrics-back:
    container_name: hydrometrics-back
    build:
     context: ./hydrometrics-main-back/
     dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
      - "587:587"
    environment:
      PORT: 8080
      PORT_SMTP: 587
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DATA_PROCESSOR_HOST: dataprocessor
      DATA_PROCESSOR_PROTOCOL: http
      DATA_PROCESSOR_PORT: 8081 
    networks:
      - hydrometrics-net
    restart: always
  # ? Configuracion data-process
  dataprocessor:
    container_name: dataprocessor
    build:
     context: ./data-processor/
     dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
    environment:
      PORT: 8081
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - hydrometrics-net
    depends_on:
      - hydrometrics-back
    restart: always 
networks:
  hydrometrics-net:
    name: hydrometrics-net





